cmake -G $1 -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS -DENABLE_SANITIZERS  \
      -DENABLE_SANITIZER_LEAK  -DENABLE_SANITIZER_ADDRESS                   \
      -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR -DENABLE_CCACHE -DENABLE_TESTS  \
      -S . -B ./build